Filme/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import listagem, inicio
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('listagem/', listagem, name="listagem"),
    path('', inicio),
    path("accounts/", include("allauth.urls")),
    path("", include("core.urls", namespace="core")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("agenda/", views.listagem_agenda, name="listagem_agenda"),
    path("", views.HomePageView.as_view(), name="listagem"),
    path("mudar_agenda_status/<int:pk>/", views.mudar_status_agenda, name="mudar_status_agenda"),
    path("agendar/<int:pk>/", views.agendar, name="agendar"),
    path("altera-ep-temporada/", views.alterar_episodio_temporada, name="alterar_ep_temp")
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS_CHOICE = (
    ("EM_ANDAMENTO", "Em Andamento"),
    ("CONCLUIDO", "Concluido"),
    ("CANCELADO", "Cancelado"),
)


class Genero(models.Model):
    descricao = models.CharField(max_length=20)

    def __str__(self):
        return self.descricao


class Idioma(models.Model):
    idioma = models.CharField(max_length=20)

    def __str__(self):
        return self.idioma


class Conteudos(models.Model):
    titulo = models.CharField(max_length=255, verbose_name="Título")
    descricao = models.TextField(verbose_name="Descrição")
    genero = models.ManyToManyField(Genero, verbose_name="Gênero")
    idioma = models.ManyToManyField(Idioma, verbose_name="Idioma")
    nota = models.DecimalField(max_digits=3, decimal_places=1, verbose_name="Nota")
    capa = models.ImageField(upload_to="capas", null=True, blank=True)
    link = models.CharField(max_length=255, null=True, blank=True)

    def getGenero(self):
        lista = [genero[0] for genero in self.genero.all().values_list("descricao")]
        return ", ".join(lista)

    def getIdioma(self):
        lista = [idioma[0] for idioma in self.idioma.all().values_list("idioma")]
        return ", ".join(lista)

    def __str__(self):
        return self.titulo

    class Meta:
        abstract = True


class Filme(Conteudos):
    tempo_duracao = models.CharField(max_length=10, verbose_name="Tempo de Duração")


class Anime(Conteudos):
    quant_episodio = models.IntegerField(verbose_name="Quantidade de Episódio")
    status = models.CharField(max_length=20, verbose_name="Status", choices=STATUS_CHOICE)
    temporadas = models.IntegerField()


class Serie(Conteudos):
    quant_episodio = models.IntegerField(verbose_name="Quantidade de Episódio")
    status = models.CharField(max_length=20, verbose_name="Status", choices=STATUS_CHOICE)
    temporadas = models.IntegerField()


class Agenda(models.Model):
    STATUS_CHOICE = (
        ("Assistindo", "Assistindo"),
        ("Desistiu", "Desistiu"),
        ("Concluído", "Concluído"),
        ("Planejamento", "Planejamento"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, verbose_name="Status", choices=STATUS_CHOICE)
    filme = models.ForeignKey("Filme", null=True, blank=True, on_delete=models.PROTECT)
    serie = models.ForeignKey("Serie", null=True, blank=True, on_delete=models.PROTECT)
    anime = models.ForeignKey("Anime", null=True, blank=True, on_delete=models.PROTECT)
    episodio_atual = models.IntegerField(verbose_name="Episódio atual", null=True, blank=True, default=1)
    temporada_atual = models.IntegerField(verbose_name="Temporada atual", null=True, blank=True, default=1)

    def opcao(self):
        if self.status == "Assistindo":
            return 1
        elif self.status == "Desistiu":
            return 2
        elif self.status == "Concluído":
            return 3
        elif self.status == "Planejamento":
            return 4

    def get_botoes(self):
        buttons = []
        if self.status == "Assistindo":
            buttons.append(dict(label="desistir", url="?novo_status=Desistiu"))
            buttons.append(dict(label="concluir", url="?novo_status=Concluído"))
        elif self.status == "Desistiu":
            buttons.append(dict(label="planejar", url="?novo_status=Planejamento"))
        elif self.status == "Concluído":
            buttons.append(dict(label="assistindo", url="?novo_status=Assistindo"))
        elif self.status == "Planejamento":
            buttons.append(dict(label="assistindo", url="?novo_status=Assistindo"))
            buttons.append(dict(label="desistir", url="?novo_status=Desistiu"))

        print(buttons)
        return buttons

    def get_conteudo(self):
        if self.filme != None:
            return self.filme
        elif self.anime != None:
            return self.anime
        elif self.serie != None:
            return self.serie

    def get_categoria(self):
        if self.filme != None:
            return "Filme"
        elif self.anime != None:
            return "Anime"
        elif self.serie != None:
            return "Serie"

core/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from .models import Filme, Serie, Anime, Agenda
from django.http import JsonResponse


class HomePageView(TemplateView):
    template_name = "listagem.html"

@login_required
def listagem(request):
    context = {}
    context['filmes'] = Filme.objects.all()
    context['series'] = Serie.objects.all()
    context['animes'] = Anime.objects.all()

    return render(request, 'core/listagem.html', context)

@login_required
def listagem_agenda(request):
    context = {}

    context['assistindos'] = Agenda.objects.filter(user=request.user, status = "Assistindo")
    context['planejamentos'] = Agenda.objects.filter(user=request.user, status="Planejamento")
    context['concluidos'] = Agenda.objects.filter(user=request.user, status="Concluído")
    context['desistindos'] = Agenda.objects.filter(user=request.user, status="Desistiu")

    return render(request, 'core/listagem_agenda.html', context)


def inicio(request):
    return render(request, 'core/inicio.html')


def mudar_status_agenda(request, pk):
    novo_status = request.GET.get("novo_status", None)

    print(novo_status)
    print(pk)

    if pk != None and novo_status != None:
        print("ENTROU")
        Agenda.objects.filter(pk=pk).update(status=novo_status)
    return redirect("core:listagem_agenda")


def agendar(request, pk):
    status = request.GET.get("status", None)
    if Filme.objects.filter(pk=pk).exists():
        filme = Filme.objects.get(pk=pk)
        Agenda.objects.create(filme=filme, user=request.user, status=status)

    elif Serie.objects.filter(pk=pk).exists():
        serie = Serie.objects.get(pk=pk)
        Agenda.objects.create(serie=serie, user=request.user, status=status)

    elif Anime.objects.filter(pk=pk).exists():
        anime = Anime.objects.get(pk=pk)
        Agenda.objects.create(anime=anime, user=request.user, status=status)

    return redirect("listagem")



#tipo = filme ou anime
#numero_ep_ou_temporada = numero referente ao ep ou a temporada (que foi alterado)
#tipo_ep_ou_temporada = se é ep ou a temporada que está sendo alterado


def alterar_episodio_temporada(request):

    direcao = request.GET.get('direcao', None)
    idAgenda = request.GET.get('idAgenda', None)
    epOuTemp = request.GET.get('epOuTemp', None)


    agenda = Agenda.objects.get(pk = idAgenda)

    if direcao == "voltar":
        if epOuTemp == "ep":
            agenda.episodio_atual = agenda.episodio_atual - 1
        elif epOuTemp == "temp":
            agenda.temporada_atual = agenda.temporada_atual - 1
    elif direcao == "proximo":
        if epOuTemp == "ep":
            agenda.episodio_atual = agenda.episodio_atual + 1
        elif epOuTemp == "temp":
            agenda.temporada_atual = agenda.temporada_atual + 1

    agenda.save()

    return JsonResponse(
        {epOuTemp: agenda.episodio_atual if epOuTemp == "ep" else agenda.temporada_atual}
    )

core/templates/core/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">SALVAR</button>
</form>
</body>
</html>

core/templates/core/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio</title>

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="#page-top"><img src="assets/img/navbar-logo.svg" alt="..." /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ms-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                    <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#team">Team</a></li>
                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
     <!-- Bootstrap core JS-->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
     <!-- Core theme JS-->
     <script src="js/scripts.js"></script>
     <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
     <!-- * *                               SB Forms JS                               * *-->
     <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
     <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
     <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

core/templates/core/inicio.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pagina inicial</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="{% static 'https://use.fontawesome.com/releases/v5.15.4/js/all.js' %}"
            crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="{% static 'core/https://fonts.googleapis.com/css?family=Montserrat:400,700' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'core/https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' %}"
          rel="stylesheet" type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet"/>
</head>
<style>
    #imgpos2 {
        position: absolute;
        left: 150px;
        top: 90%
    }
    h6 {
        position: absolute;
        left: 300px;
        top: 90%

    }



</style>
<body id="page-top">

<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-heading text-uppercase">Bem Vindo ao Mundo de Entreterimento!</div>
        <div class="masthead-subheading">Divirtam-se</div>
        <a class="btn btn-primary  text-uppercase" href="http://127.0.0.1:8000/accounts/login/">Login</a>
        <a class="btn btn-primary  text-uppercase" href="http://127.0.0.1:8000/accounts/signup/">Cadastro</a>
    </div>
    <div>
        <img src="{% static 'core/assets/img/navbar-logo123.png' %}" alt="image" height="50" width="" id="imgpos2"/>
        <h6> A empresa World of Imagination apresenta um site para buscar Extra Entertainment!!
            Desenvolvedores: Anderson Silva / Rafaéla Moura
            <p> Contatos para suporte: (87) 98888-8888 / (87) 79999-8888</p></h6>

        <h6></h6>
    </div>
</header>


<!-- Bootstrap core JS-->
<script src="{ % static 'core/https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js' %}"></script>
<!-- Core theme JS-->
<script src="{% static 'core/js/scripts.js' %}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="{% static 'core/https://cdn.startbootstrap.com/sb-forms-latest.js' %}"></script>

</body>
</html>

core/templates/core/listagem_agenda.html
<!doctype html>
<html lang="pt-br">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Agenda</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<style>
    #imgpos2 {
        position: absolute;
        left: 0px;
    }
</style>
<body style="background-color: whitesmoke;">

<h1>
    <img src="{% static 'core/assets/img/navbar-logo123.png' %}" alt="image" height="90" width="" id="imgpos2"/>
</h1>

<center style = "color: RoyalBlue; font-size : 50px" > Minha Agenda </center>
<div class="m-3">


    <div class="row d-flex justify-content-center">
        <ul class="nav nav-pills justify-content-center mt-2 mb-4 p-2 bg-light w-50 shadow rounded " id="myTab"
            role="tablist">

            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="assistindo-tab" data-bs-toggle="tab"
                        data-bs-target="#assistindo" type="button" role="tab" aria-controls="assistindo"
                        aria-selected="false">ASSISTINDO
                </button>
            </li>

            <li class="nav-item" role="presentation">
                <button class="nav-link" id="planejando-tab" data-bs-toggle="tab" data-bs-target="#planejando"
                        type="button" role="tab" aria-controls="planejando" aria-selected="false">PLANEJANDO
                </button>
            </li>

            <li class="nav-item" role="presentation">
                <button class="nav-link" id="concluido-tab" data-bs-toggle="tab" data-bs-target="#concluido"
                        type="button" role="tab" aria-controls="concluido" aria-selected="false">CONCLUÍDO
                </button>
            </li>

            <li class="nav-item" role="presentation">
                <button class="nav-link" id="desistidos-tab" data-bs-toggle="tab" data-bs-target="#desistidos"
                        type="button" role="tab" aria-controls="desistidos" aria-selected="false">DROPADO
                </button>
            </li>


        </ul>
    </div>

    <div class="tab-content rounded" id="myTabContent">

        <div class="tab-pane fade show active" id="assistindo" role="tabpanel" aria-labelledby="assistindo-tab">
            <table class="table table-bordered shadow rounded">
                <thead class="table-dark">
                <tr class="text-center">
                    <th scope="col">Título</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Status</th>
                    <th scope="col">Episódio</th>
                    <th scope="col">Temporada</th>
                    <th scope="col">Assistir</th>
                </tr>
                </thead>
                <tbody>
                {% for assistindo in assistindos %}
                <tr class="align-middle">
                    <th class="text-center">{{assistindo.get_conteudo.titulo}}</th>
                    <td class="text-center">{{assistindo.get_categoria}}</td>
                    <td class="text-center">

                        <a href="{% url 'core:mudar_status_agenda' assistindo.id %}?novo_status=Concluído"
                           class="btn btn-success" style="width: 30%;" data-bs-toggle="tooltip"
                           data-bs-placement="bottom" title="Mudar para concluído">
                            <i class="fas fa-check"></i></a>

                        <a href="{% url 'core:mudar_status_agenda' assistindo.id %}?novo_status=Desistiu"
                           class="btn btn-danger" style="width: 30%;" data-bs-toggle="tooltip"
                           data-bs-placement="bottom" title="Mudar para desistindo"><i
                                class="fas fa-times"></i></i></a>
                    </td>

                    <td class="text-center align-middle">
                        <div class="d-flex justify-content-center align-itens-center">

                            <button type="button" onclick="trocarEpTemporada('voltar', {{assistindo.pk}}, 'ep')"
                                    class="btn btn-primary btn-sm"><i class="fas fa-minus"></i>
                            </button>
                            <p id="ep_{{assistindo.pk}}" class="form-control w-25 mb-0">
                                {{assistindo.episodio_atual}}</p>
                            <button type="button" onclick="trocarEpTemporada('proximo', {{assistindo.pk}}, 'ep')"
                                    class="btn btn-primary btn-sm"><i class="fas fa-plus"></i>
                            </button>

                        </div>
                    </td>

                    <td class="text-center align-middle">
                        <div class="d-flex justify-content-center align-itens-center">
                            <button type="button" onclick="trocarEpTemporada('voltar', {{assistindo.pk}}, 'temp')"
                                    class="btn btn-primary btn-sm"><i class="fas fa-minus"></i>
                            </button>
                            <p id="temp_{{assistindo.pk}}" class="form-control w-25 mb-0">
                                {{assistindo.temporada_atual}}</p>
                            <button type="button" onclick="trocarEpTemporada('proximo', {{assistindo.pk}}, 'temp')"
                                    class="btn btn-primary btn-sm"><i class="fas fa-plus"></i>
                            </button>
                        </div>
                    </td>

                    <td class="text-center">

                        <a class="btn btn-dark" data-bs-toggle="tooltip" data-bs-placement="bottom"
                           href="{{assistindo.get_conteudo.link}}" target="_blank"
                           title="Assistir agora !">
                            <i class="fas fa-film"></i>
                        </a>

                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="planejando" role="tabpanel" aria-labelledby="planejando-tab">
            <table class="table table-bordered shadow rounded">
                <thead class="table-dark">
                <tr class="text-center">
                    <th scope="col">Título</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                {% for planejamento in planejamentos %}
                <tr class="align-middle">
                    <th class="text-center">{{planejamento.get_conteudo.titulo}}</th>
                    <td class="text-center">{{planejamento.get_categoria}}</td>
                    <td class="text-center">
                        <a href="{% url 'core:mudar_status_agenda' planejamento.id %}?novo_status=Assistindo"
                           class="btn btn-secondary"  style="width: 30%;" data-bs-toggle="tooltip"
                           data-bs-placement="bottom" title="Mudar para assistindo">
                            <i class="fas fa-play"></i></a>

                        <a href="{% url 'core:mudar_status_agenda' planejamento.id %}?novo_status=Desistiu"
                           class="btn btn-danger" style="width: 30%;" data-bs-toggle="tooltip"
                           data-bs-placement="bottom" title="Mudar para desistindo"><i
                                class="fas fa-times"></i></i></a>
                    </td>
                </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
        <div class="tab-pane fade" id="concluido" role="tabpanel" aria-labelledby="concluido-tab">
            <table class="table table-bordered shadow rounded">
                <thead class="table-dark">
                <tr class="text-center">
                    <th scope="col">Título</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                {% for concluido in concluidos %}
                <tr class="align-middle">
                    <th class="text-center">{{concluido.get_conteudo.titulo}}</th>
                    <td class="text-center">{{concluido.get_categoria}}</td>
                    <td class="text-center">

                        <a href="{% url 'core:mudar_status_agenda' concluido.id %}?novo_status=Assistindo"
                           class="btn btn-secondary"  style="width: 30%;" data-bs-toggle="tooltip"
                           data-bs-placement="bottom" title="Mudar para assistindo">
                            <i class="fas fa-play"></i></a>


                    </td>
                </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
        <div class="tab-pane fade" id="desistidos" role="tabpanel" aria-labelledby="desistidos-tab">
            <table class="table table-bordered shadow rounded">
                <thead class="table-dark">
                <tr class="text-center">
                    <th scope="col">Título</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                {% for desistindo in desistindos %}
                <tr class="align-middle">
                    <th class="text-center">{{desistindo.get_conteudo.titulo}}</th>
                    <td class="text-center">{{desistindo.get_categoria}}</td>
                    <td class="text-center">

                        <a href="{% url 'core:mudar_status_agenda' desistindo.id %}?novo_status=Planejamento"
                           class="btn btn-warning" style="width: 30%;" data-bs-toggle="tooltip"
                           data-bs-placement="bottom" title="Mudar para planejando"><i
                                class="fas fa-clock"></i></i></a>


                    </td>

                </tr>

                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
</div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/a807871457.js" crossorigin="anonymous"></script>
<script>

        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })

</script>
<!--Axios - Requisições Assincronas-->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>


<script>
    function openNewTab(url){
        window.open(url, '_blank').focus(); //Abrir um nova janela com o link do filme/serie/anime
    }


    function trocarEpTemporada(direcao, idAgenda, epOuTemp){

        let url = `/altera-ep-temporada/?direcao=${direcao}&idAgenda=${idAgenda}&epOuTemp=${epOuTemp}`

        axios.get(url)
          .then(function (response) {

            console.log(response)

            if (epOuTemp === "ep"){
                const displayEpisodio = document.getElementById(`ep_${idAgenda}`)

                displayEpisodio.innerHTML = response.data.ep;


            }
            else if (epOuTemp === "temp"){
                const displayTemporada = document.getElementById(`temp_${idAgenda}`)
                console.log(displayTemporada);
                displayTemporada.innerHTML = response.data.temp;
            }
          })

    }


</script>

</body>
</html>